export const SET_LABELS = {
  gladiators_finale: "角斗士的终幕礼",
  wanderers_troupe: "流浪大地的乐团",
  noblesse_oblige: "昔日宗室之仪",
  bloodstained_chivalry: "染血的骑士道",
  maiden_beloved: "被怜爱的少女",
  viridescent_venerer: "翠绿之影",
  archaic_petra: "悠古的磐岩",
  retracing_bolide: "逆飞的流星",
  thundersoother: "平息鸣雷的尊者",
  thundering_fury: "如雷的盛怒",
  lavawalker: "渡过烈火的贤人",
  crimson_witch_of_flames: "炽烈的炎之魔女",
  blizzard_strayer: "冰风迷途的勇士",
  heart_of_depth: "沉沦之心",
  tenacity_of_the_millelith: "千岩牢固",
  pale_flame: "苍白之火",
  shimenawas_reminiscence: "追忆之注连",
  emblem_of_severed_fate: "绝缘之旗印",
  husk_of_opulent_dreams: "华馆梦醒形骸记",
  ocean_hued_clam: "海染砗磲",
  vermillion_hereafter: "辰砂往生录",
  echoes_of_an_offering: "来歆余响",
  deepwood_memories: "深林的记忆",
  gilded_dreams: "饰金之梦",
  desert_pavilion_chronicle: "沙上楼阁史话",
  flower_of_paradise_lost: "乐园遗落之花",
  nymphs_dream: "水仙之梦",
  vourukashas_glow: "花海甘露之光",
  marechaussee_hunter: "逐影猎人",
  golden_troupe: "黄金剧团",
  song_of_days_past: "昔时之歌",
  nighttime_whispers_in_the_echoing_woods: "回声之林夜话",
  fragment_of_harmonic_whimsy: "谐律异想断章",
  unfinished_reverie: "未竟的遐思",
  scroll_of_the_hero_of_cinder_city: "烬城勇者绘卷",
  obsidian_codex: "黑曜秘典",
  long_nights_oath: "长夜之誓",
  finale_of_the_deep_galleries: "深廊终曲",
  night_of_the_skys_unveiling: "穹境示现之夜",
  silken_moons_serenade: "纺月的夜歌",
  a_day_carved_from_rising_winds: "风起之日",
  aubade_of_morningstar_and_moon: "晨星与月的晓歌",
  celestial_gift: "天之美赐",
  disenchantment_in_deep_shadow: "影中沉凝的幻灭",

  passerby_of_wandering_cloud: "云无留迹的过客",
  musketeer_of_wild_wheat: "野穗伴行的快枪手",
  knight_of_purity_palace: "净庭教宗的圣骑士",
  hunter_of_glacial_forest: "密林卧雪的猎人",
  champion_of_streetwise_boxing: "街头出身的拳王",
  guard_of_wuthering_snow: "戍卫风雪的铁卫",
  firesmith_of_lava_forging: "熔岩锻铸的火匠",
  genius_of_brilliant_stars: "繁星璀璨的天才",
  band_of_sizzling_thunder: "激奏雷电的乐队",
  eagle_of_twilight_line: "晨昏交界的翔鹰",
  thief_of_shooting_meteor: "流星追迹的怪盗",
  wastelander_of_banditry_desert: "盗匪荒漠的废土客",
  longevous_disciple: "宝命长存的莳者",
  messenger_traversing_hackerspace: "骇域漫游的信使",
  the_ashblazing_grand_duke: "毁烬焚骨的大公",
  prisoner_in_deep_confinement: "幽锁深牢的系囚",
  pioneer_diver_of_dead_waters: "死水深潜的先驱",
  watchmaker_master_of_dream_machinations: "机心戏梦的钟表匠",
  iron_cavalry_against_the_scourge: "荡除蠹灾的铁骑",
  the_wind_soaring_valorous: "风举云飞的勇烈",
  sacerdos_relived_ordeal: "重循苦旅的司铎",
  scholar_lost_in_erudition: "识海迷坠的学者",
  hero_of_triumphant_song: "凯歌祝捷的英豪",
  poet_of_mourning_collapse: "哀歌覆国的诗人",
  warrior_goddess_of_sun_and_thunder: "烈阳惊雷的女武神",
  wavestrider_captain: "恶海逐波的船长",
  world_remaking_deliverer: "再创天地的救世主",
  self_enshrouded_recluse: "自匿星芒的隐士",
  ever_glorious_magical_girl: "闪耀功勋的魔法少女",
  diviner_of_distant_reach: "应天涉远的卜者",
  artisan_of_ingenious_inquiry: "叩问天工的名冶",
  navigator_of_stars_as_i_see: "星如我见的领航员",

  space_sealing_station: "太空封印站",
  fleet_of_the_ageless: "不老者的仙舟",
  pan_cosmic_commercial_enterprise: "泛银河商业公司",
  belobog_of_the_architects: "筑城者的贝洛伯格",
  celestial_differentiator: "星体差分机",
  inert_salsotto: "停转的萨尔索图",
  talia_kingdom_of_banditry: "盗贼公国塔利亚",
  sprightly_vonwacq: "生命的翁瓦克",
  rutilant_arena: "繁星竞技场",
  broken_keel: "折断的龙骨",
  firmament_frontline_glamoth: "苍穹战线格拉默",
  penacony_land_of_the_dreams: "梦想之地匹诺康尼",
  sigonia_the_unclaimed_desolation: "无主荒星茨冈尼亚",
  izumo_gensei_and_takama_divine_realm: "出云显世与高天神国",
  duran_dynasty_of_running_wolves: "奔狼的都蓝王朝",
  forge_of_the_kalpagni_lantern: "劫火莲灯铸炼宫",
  lushaka_the_sunken_seas: "沉陆海域露莎卡",
  the_wondrous_bananamusement_park: "奇想蕉乐园",
  amphoreus_the_eternal_land: "永恒之地翁法罗斯",
  bone_collections_serene_demesne: "谧宁拾骨地",
  revelry_by_the_sea: "沉欢醉饮的海隅",
  giant_tree_of_rapt_brooding: "渊思寂虑的巨树",
  city_of_converging_stars: "千星荟萃之城",
  punklorde_stage_zero: "零号关卡朋克洛德",
  tengoku_livestream: "天国@直播间",
  arcadia_of_woven_dreams: "妖精织梦的乐园",
};

const pool = (id, name, sets) => ({ id, name, sets });

const GENSHIN_DOMAIN_POOLS = [
  pool("genshin-domain-crown-of-the-mountain-wind", "山风的荆冕", ["celestial_gift", "disenchantment_in_deep_shadow"]),
  pool("genshin-domain-moonchilds-treasures", "月童的库藏", ["aubade_of_morningstar_and_moon", "a_day_carved_from_rising_winds"]),
  pool("genshin-domain-frostladen-machinery", "霜凝的机枢", ["night_of_the_skys_unveiling", "silken_moons_serenade"]),
  pool("genshin-domain-derelict-masonry-dock", "荒废砌造坞", ["finale_of_the_deep_galleries", "long_nights_oath"]),
  pool("genshin-domain-sanctum-of-rainbow-spirits", "虹灵的净土", ["scroll_of_the_hero_of_cinder_city", "obsidian_codex"]),
  pool("genshin-domain-faded-theater", "褪色的剧场", ["unfinished_reverie", "fragment_of_harmonic_whimsy"]),
  pool("genshin-domain-waterfall-wen", "临瀑之城", ["nighttime_whispers_in_the_echoing_woods", "song_of_days_past"]),
  pool("genshin-domain-denouement-of-sin", "罪祸的终末", ["marechaussee_hunter", "golden_troupe"]),
  pool("genshin-domain-molten-iron-fortress", "熔铁的孤塞", ["nymphs_dream", "vourukashas_glow"]),
  pool("genshin-domain-city-of-gold", "赤金的城墟", ["flower_of_paradise_lost", "desert_pavilion_chronicle"]),
  pool("genshin-domain-spire-of-solitary-enlightenment", "缘觉塔", ["deepwood_memories", "gilded_dreams"]),
  pool("genshin-domain-the-lost-valley", "岩中幽谷", ["echoes_of_an_offering", "vermillion_hereafter"]),
  pool("genshin-domain-slumbering-court", "沉眠之庭", ["husk_of_opulent_dreams", "ocean_hued_clam"]),
  pool("genshin-domain-momiji-dyed-court", "椛染之庭", ["emblem_of_severed_fate", "shimenawas_reminiscence"]),
  pool("genshin-domain-ridge-watch", "山脊守望", ["tenacity_of_the_millelith", "pale_flame"]),
  pool("genshin-domain-peak-of-vindagnyr", "芬德尼尔之顶", ["blizzard_strayer", "heart_of_depth"]),
  pool("genshin-domain-midsummer-courtyard", "仲夏庭园", ["thundering_fury", "thundersoother"]),
  pool("genshin-domain-domain-of-guyun", "孤云凌霄之处", ["archaic_petra", "retracing_bolide"]),
  pool("genshin-domain-clear-pool", "华池岩岫", ["noblesse_oblige", "bloodstained_chivalry"]),
  pool("genshin-domain-hidden-palace-of-zhou", "无妄引咎密宫", ["lavawalker", "crimson_witch_of_flames"]),
  pool("genshin-domain-valley-of-remembrance", "铭记之谷", ["viridescent_venerer", "maiden_beloved"]),
];

const GENSHIN_OTHER_POOLS = [
  pool("genshin-other-crown-of-the-mountain-wind", "山风的荆冕", ["celestial_gift", "disenchantment_in_deep_shadow"]),
  pool("genshin-other-moonchilds-treasures", "月童的库藏", ["aubade_of_morningstar_and_moon", "a_day_carved_from_rising_winds"]),
  pool("genshin-other-frostladen-machinery", "霜凝的机枢", ["night_of_the_skys_unveiling", "silken_moons_serenade"]),
  pool("genshin-other-derelict-masonry-dock", "荒废砌造坞", ["finale_of_the_deep_galleries", "long_nights_oath"]),
  pool("genshin-other-sanctum-of-rainbow-spirits", "虹灵的净土", ["scroll_of_the_hero_of_cinder_city", "obsidian_codex"]),
  pool("genshin-other-faded-theater", "褪色的剧场", ["unfinished_reverie", "fragment_of_harmonic_whimsy"]),
  pool("genshin-other-waterfall-wen", "临瀑之城", ["nighttime_whispers_in_the_echoing_woods", "song_of_days_past"]),
  pool("genshin-other-denouement-of-sin", "罪祸的终末", ["marechaussee_hunter", "golden_troupe"]),
  pool("genshin-other-molten-iron-fortress", "熔铁的孤塞", ["nymphs_dream", "vourukashas_glow"]),
  pool("genshin-other-city-of-gold", "赤金的城墟", ["flower_of_paradise_lost", "desert_pavilion_chronicle"]),
  pool("genshin-other-spire-of-solitary-enlightenment", "缘觉塔", ["deepwood_memories", "gilded_dreams"]),
  pool("genshin-other-the-lost-valley", "岩中幽谷", ["echoes_of_an_offering", "vermillion_hereafter"]),
  pool("genshin-other-slumbering-court", "沉眠之庭", ["husk_of_opulent_dreams", "ocean_hued_clam"]),
  pool("genshin-other-momiji-dyed-court", "椛染之庭", ["emblem_of_severed_fate", "shimenawas_reminiscence"]),
  pool("genshin-other-ridge-watch", "山脊守望", ["tenacity_of_the_millelith", "pale_flame"]),
  pool("genshin-other-peak-of-vindagnyr", "芬德尼尔之顶", ["blizzard_strayer", "heart_of_depth"]),
  pool("genshin-other-midsummer-courtyard", "仲夏庭园", ["thundering_fury", "thundersoother"]),
  pool("genshin-other-domain-of-guyun", "孤云凌霄之处", ["archaic_petra", "retracing_bolide"]),
  pool("genshin-other-clear-pool", "华池岩岫", ["noblesse_oblige", "bloodstained_chivalry"]),
  pool("genshin-other-boss", "BOSS（首领、周本）", ["wanderers_troupe"]),
  pool("genshin-other-hidden-palace-of-zhou", "无妄引咎密宫", ["lavawalker", "crimson_witch_of_flames"]),
  pool("genshin-other-valley-of-remembrance", "铭记之谷", ["viridescent_venerer", "maiden_beloved"]),
  pool("genshin-other-elite-boss", "击杀精英级怪物 BOSS（首领、周本）", ["gladiators_finale"]),
];

const HSR_CAVERN_POOLS = [
  pool("hsr-cavern-drifting", "漂泊之径", ["passerby_of_wandering_cloud", "musketeer_of_wild_wheat"]),
  pool("hsr-cavern-holy-hymn", "圣颂之径", ["knight_of_purity_palace", "band_of_sizzling_thunder"]),
  pool("hsr-cavern-gelid-wind", "霜风之径", ["hunter_of_glacial_forest", "eagle_of_twilight_line"]),
  pool("hsr-cavern-jabbing-punch", "迅拳之径", ["champion_of_streetwise_boxing", "thief_of_shooting_meteor"]),
  pool("hsr-cavern-conflagration", "野焰之径", ["firesmith_of_lava_forging", "wastelander_of_banditry_desert"]),
  pool("hsr-cavern-providence", "睿治之径", ["guard_of_wuthering_snow", "genius_of_brilliant_stars"]),
  pool("hsr-cavern-elixir-seekers", "药使之径", ["longevous_disciple", "messenger_traversing_hackerspace"]),
  pool("hsr-cavern-darkness", "幽冥之径", ["the_ashblazing_grand_duke", "prisoner_in_deep_confinement"]),
  pool("hsr-cavern-dreamdive", "梦潜之径", ["pioneer_diver_of_dead_waters", "watchmaker_master_of_dream_machinations"]),
  pool("hsr-cavern-cavalier", "勇骑之径", ["iron_cavalry_against_the_scourge", "the_wind_soaring_valorous"]),
  pool("hsr-cavern-uncertainty", "迷识之径", ["sacerdos_relived_ordeal", "scholar_lost_in_erudition"]),
  pool("hsr-cavern-aria", "弦歌之径", ["hero_of_triumphant_song", "poet_of_mourning_collapse"]),
  pool("hsr-cavern-thundersurge", "雳涌之径", ["warrior_goddess_of_sun_and_thunder", "wavestrider_captain"]),
  pool("hsr-cavern-hidden-salvation", "隐救之径", ["world_remaking_deliverer", "self_enshrouded_recluse"]),
  pool("hsr-cavern-divination", "魔占之径", ["diviner_of_distant_reach", "ever_glorious_magical_girl"]),
  pool("hsr-cavern-firewatch", "观火之径", ["artisan_of_ingenious_inquiry", "navigator_of_stars_as_i_see"]),
];

const HSR_PLANAR_POOLS = [
  pool("hsr-planar-fortress-unbroken", "差分宇宙：坚城不倒", ["space_sealing_station", "fleet_of_the_ageless"]),
  pool("hsr-planar-firesteel-heart", "差分宇宙：浴火钢心", ["talia_kingdom_of_banditry", "sprightly_vonwacq"]),
  pool("hsr-planar-gentle-words", "差分宇宙：温柔话语", ["pan_cosmic_commercial_enterprise", "celestial_differentiator"]),
  pool("hsr-planar-centennial-frost", "差分宇宙：百年冻土", ["belobog_of_the_architects", "inert_salsotto"]),
  pool("hsr-planar-fruit-of-evil", "差分宇宙：孽果盘生", ["rutilant_arena", "broken_keel"]),
  pool("hsr-planar-swords-like-rain", "差分宇宙：天剑如雨", ["firmament_frontline_glamoth", "penacony_land_of_the_dreams"]),
  pool("hsr-planar-sleep-beside-you", "差分宇宙：伴你入眠", ["sigonia_the_unclaimed_desolation", "izumo_gensei_and_takama_divine_realm"]),
  pool("hsr-planar-eternal-comedy", "差分宇宙：永恒笑剧", ["duran_dynasty_of_running_wolves", "forge_of_the_kalpagni_lantern"]),
  pool("hsr-planar-ravenous-insects", "差分宇宙：蠹役饥肠", ["lushaka_the_sunken_seas", "the_wondrous_bananamusement_park"]),
  pool("hsr-planar-endless-strife", "差分宇宙：纷争不休", ["giant_tree_of_rapt_brooding", "bone_collections_serene_demesne"]),
  pool("hsr-planar-vermilion-moon", "差分宇宙：月下朱殷", ["revelry_by_the_sea", "arcadia_of_woven_dreams"]),
  pool("hsr-planar-westwind-thicket", "差分宇宙：西风丛中", ["tengoku_livestream", "amphoreus_the_eternal_land"]),
  pool("hsr-planar-gilded-remembrance", "差分宇宙：鎏金追忆", ["punklorde_stage_zero", "city_of_converging_stars"]),
];

export const SET_POOLS = {
  genshin: {
    domain: GENSHIN_DOMAIN_POOLS,
    other: GENSHIN_OTHER_POOLS,
  },
  hsr: {
    cavern: HSR_CAVERN_POOLS,
    planar: HSR_PLANAR_POOLS,
  },
};

export function flattenPools(pools) {
  return [...new Set(pools.flatMap((item) => item.sets))];
}
