export const SET_LABELS = {
  gladiators_finale: "角斗士的终幕礼",
  wanderers_troupe: "流浪大地的乐团",
  noblesse_oblige: "昔日宗室之仪",
  bloodstained_chivalry: "染血的骑士道",
  maiden_beloved: "被怜爱的少女",
  viridescent_venerer: "翠绿之影",
  archaic_petra: "悠古的磐岩",
  retracing_bolide: "逆飞的流星",
  thundersoother: "平息鸣雷的尊者",
  thundering_fury: "如雷的盛怒",
  lavawalker: "渡过烈火的贤人",
  crimson_witch_of_flames: "炽烈的炎之魔女",
  blizzard_strayer: "冰风迷途的勇士",
  heart_of_depth: "沉沦之心",
  tenacity_of_the_millelith: "千岩牢固",
  pale_flame: "苍白之火",
  shimenawas_reminiscence: "追忆之注连",
  emblem_of_severed_fate: "绝缘之旗印",
  husk_of_opulent_dreams: "华馆梦醒形骸记",
  ocean_hued_clam: "海染砗磲",
  vermillion_hereafter: "辰砂往生录",
  echoes_of_an_offering: "来歆余响",
  deepwood_memories: "深林的记忆",
  gilded_dreams: "饰金之梦",
  desert_pavilion_chronicle: "沙上楼阁史话",
  flower_of_paradise_lost: "乐园遗落之花",
  nymphs_dream: "水仙之梦",
  vourukashas_glow: "花海甘露之光",
  marechaussee_hunter: "逐影猎人",
  golden_troupe: "黄金剧团",
  song_of_days_past: "昔时之歌",
  nighttime_whispers_in_the_echoing_woods: "回声之林夜话",
  fragment_of_harmonic_whimsy: "谐律异想断章",
  unfinished_reverie: "未竟的遐思",
  scroll_of_the_hero_of_cinder_city: "烬城勇者绘卷",
  obsidian_codex: "黑曜秘典",
  long_nights_oath: "长夜之誓",
  finale_of_the_deep_galleries: "深廊终曲",
  night_of_the_skys_unveiling: "穹境示现之夜",
  silken_moons_serenade: "纺月的夜歌",
  a_day_carved_from_rising_winds: "穹风铸境之日",
  aubade_of_morningstar_and_moon: "晨星与月的咏叹",
  celestial_gift: "天穹赐礼",
  disenchantment_in_deep_shadow: "深影破魅",

  passerby_of_wandering_cloud: "云无留迹的过客",
  musketeer_of_wild_wheat: "野穗伴行的快枪手",
  knight_of_purity_palace: "净庭教宗的圣骑士",
  hunter_of_glacial_forest: "密林卧雪的猎人",
  champion_of_streetwise_boxing: "街头出身的拳王",
  guard_of_wuthering_snow: "戍卫风雪的铁卫",
  firesmith_of_lava_forging: "熔岩锻铸的火匠",
  genius_of_brilliant_stars: "繁星璀璨的天才",
  band_of_sizzling_thunder: "激奏雷电的乐队",
  eagle_of_twilight_line: "晨昏交界的翔鹰",
  thief_of_shooting_meteor: "流星追迹的怪盗",
  wastelander_of_banditry_desert: "盗匪荒漠的废土客",
  longevous_disciple: "宝命长存的莳者",
  messenger_traversing_hackerspace: "骇域漫游的信使",
  the_ashblazing_grand_duke: "毁烬焚骨的大公",
  prisoner_in_deep_confinement: "幽锁深牢的系囚",
  pioneer_diver_of_dead_waters: "死水深潜的先驱",
  watchmaker_master_of_dream_machinations: "机心戏梦的钟表匠",
  iron_cavalry_against_the_scourge: "荡除蠹灾的铁骑",
  the_wind_soaring_valorous: "风举云飞的勇烈",
  sacerdos_relived_ordeal: "重循苦旅的司铎",
  scholar_lost_in_erudition: "识海迷坠的学者",
  hero_of_triumphant_song: "凯歌祝捷的英豪",
  poet_of_mourning_collapse: "哀歌覆国的诗人",
  warrior_goddess_of_sun_and_thunder: "烈阳惊雷的女武神",
  wavestrider_captain: "踏浪船长",
  world_remaking_deliverer: "重塑世界的救世主",
  self_enshrouded_recluse: "自匿星芒的隐士",
  ever_glorious_magical_girl: "永恒光辉的魔法少女",
  diviner_of_distant_reach: "远瞩占卜师",

  space_sealing_station: "太空封印站",
  fleet_of_the_ageless: "不老者的仙舟",
  pan_cosmic_commercial_enterprise: "泛银河商业公司",
  belobog_of_the_architects: "筑城者的贝洛伯格",
  celestial_differentiator: "星体差分机",
  inert_salsotto: "停转的萨尔索图",
  talia_kingdom_of_banditry: "盗贼公国塔利亚",
  sprightly_vonwacq: "生命的翁瓦克",
  rutilant_arena: "繁星竞技场",
  broken_keel: "折断的龙骨",
  firmament_frontline_glamoth: "苍穹战线格拉默",
  penacony_land_of_the_dreams: "梦想之地匹诺康尼",
  sigonia_the_unclaimed_desolation: "无主荒星茨冈尼亚",
  izumo_gensei_and_takama_divine_realm: "出云显世与高天神国",
  duran_dynasty_of_running_wolves: "奔狼的都蓝王朝",
  forge_of_the_kalpagni_lantern: "劫火莲灯铸炼宫",
  lushaka_the_sunken_seas: "沉陆海域露莎卡",
  the_wondrous_bananamusement_park: "奇想蕉乐园",
  amphoreus_the_eternal_land: "永恒之地翁法罗斯",
  bone_collections_serene_demesne: "静谧拾骨地",
  revelry_by_the_sea: "海隅欢宴",
  giant_tree_of_rapt_brooding: "沉思巨树",
  city_of_converging_stars: "汇星之城",
  punklorde_stage_zero: "庞克洛德零号舞台",
  tengoku_livestream: "天国直播",
  arcadia_of_woven_dreams: "织梦乐园阿卡迪亚",
};

const pool = (id, name, sets) => ({ id, name, sets });

export const SET_POOLS = {
  genshin: {
    domain: [
      pool("clear-pool", "华池岩岫", ["noblesse_oblige", "bloodstained_chivalry"]),
      pool("valley-of-remembrance", "铭记之谷", ["maiden_beloved", "viridescent_venerer"]),
      pool("domain-of-guyun", "孤云凌霄之处", ["archaic_petra", "retracing_bolide"]),
      pool("midsummer-courtyard", "仲夏庭园", ["thundersoother", "thundering_fury"]),
      pool("hidden-palace-of-zhou", "无妄引咎密宫", ["lavawalker", "crimson_witch_of_flames"]),
      pool("peak-of-vindagnyr", "芬德尼尔之顶", ["blizzard_strayer", "heart_of_depth"]),
      pool("ridge-watch", "山脊守望", ["tenacity_of_the_millelith", "pale_flame"]),
      pool("momiji-dyed-court", "椛染之庭", ["shimenawas_reminiscence", "emblem_of_severed_fate"]),
      pool("slumbering-court", "沉眠之庭", ["husk_of_opulent_dreams", "ocean_hued_clam"]),
      pool("the-lost-valley", "岩中幽谷", ["vermillion_hereafter", "echoes_of_an_offering"]),
      pool("spire-of-solitary-enlightenment", "缘觉塔", ["deepwood_memories", "gilded_dreams"]),
      pool("city-of-gold", "赤金的城墟", ["desert_pavilion_chronicle", "flower_of_paradise_lost"]),
      pool("molten-iron-fortress", "熔铁的孤塞", ["nymphs_dream", "vourukashas_glow"]),
      pool("denouement-of-sin", "罪祸的终末", ["marechaussee_hunter", "golden_troupe"]),
      pool("waterfall-wen", "临瀑之城", ["song_of_days_past", "nighttime_whispers_in_the_echoing_woods"]),
      pool("faded-theater", "褪色的剧场", ["fragment_of_harmonic_whimsy", "unfinished_reverie"]),
      pool("sanctum-of-rainbow-spirits", "虹灵的净土", ["scroll_of_the_hero_of_cinder_city", "obsidian_codex"]),
      pool("trounce-domain-55", "幽境危战", ["long_nights_oath", "finale_of_the_deep_galleries"]),
      pool("moonchilds-treasures", "月谕珍藏", ["night_of_the_skys_unveiling", "silken_moons_serenade"]),
      pool("rising-winds", "升风秘境", ["a_day_carved_from_rising_winds", "aubade_of_morningstar_and_moon"]),
      pool("deep-shadow", "深影秘境", ["celestial_gift", "disenchantment_in_deep_shadow"]),
    ],
    other: [
      pool("boss-world", "首领与周本常驻池", ["gladiators_finale", "wanderers_troupe"]),
      pool("clear-pool", "华池岩岫", ["noblesse_oblige", "bloodstained_chivalry"]),
      pool("valley-of-remembrance", "铭记之谷", ["maiden_beloved", "viridescent_venerer"]),
      pool("domain-of-guyun", "孤云凌霄之处", ["archaic_petra", "retracing_bolide"]),
      pool("midsummer-courtyard", "仲夏庭园", ["thundersoother", "thundering_fury"]),
      pool("hidden-palace-of-zhou", "无妄引咎密宫", ["lavawalker", "crimson_witch_of_flames"]),
      pool("peak-of-vindagnyr", "芬德尼尔之顶", ["blizzard_strayer", "heart_of_depth"]),
      pool("ridge-watch", "山脊守望", ["tenacity_of_the_millelith", "pale_flame"]),
      pool("momiji-dyed-court", "椛染之庭", ["shimenawas_reminiscence", "emblem_of_severed_fate"]),
      pool("slumbering-court", "沉眠之庭", ["husk_of_opulent_dreams", "ocean_hued_clam"]),
      pool("the-lost-valley", "岩中幽谷", ["vermillion_hereafter", "echoes_of_an_offering"]),
      pool("spire-of-solitary-enlightenment", "缘觉塔", ["deepwood_memories", "gilded_dreams"]),
      pool("city-of-gold", "赤金的城墟", ["desert_pavilion_chronicle", "flower_of_paradise_lost"]),
      pool("molten-iron-fortress", "熔铁的孤塞", ["nymphs_dream", "vourukashas_glow"]),
      pool("denouement-of-sin", "罪祸的终末", ["marechaussee_hunter", "golden_troupe"]),
      pool("waterfall-wen", "临瀑之城", ["song_of_days_past", "nighttime_whispers_in_the_echoing_woods"]),
      pool("faded-theater", "褪色的剧场", ["fragment_of_harmonic_whimsy", "unfinished_reverie"]),
      pool("sanctum-of-rainbow-spirits", "虹灵的净土", ["scroll_of_the_hero_of_cinder_city", "obsidian_codex"]),
      pool("trounce-domain-55", "幽境危战", ["long_nights_oath", "finale_of_the_deep_galleries"]),
      pool("moonchilds-treasures", "月谕珍藏", ["night_of_the_skys_unveiling", "silken_moons_serenade"]),
      pool("rising-winds", "升风秘境", ["a_day_carved_from_rising_winds", "aubade_of_morningstar_and_moon"]),
      pool("deep-shadow", "深影秘境", ["celestial_gift", "disenchantment_in_deep_shadow"]),
    ],
  },
  hsr: {
    cavern: [
      pool("drifting", "漂泊之径", ["passerby_of_wandering_cloud", "musketeer_of_wild_wheat"]),
      pool("holy-hymn", "圣颂之径", ["knight_of_purity_palace", "band_of_sizzling_thunder"]),
      pool("gelid-wind", "霜风之径", ["hunter_of_glacial_forest", "eagle_of_twilight_line"]),
      pool("jabbing-punch", "迅拳之径", ["champion_of_streetwise_boxing", "thief_of_shooting_meteor"]),
      pool("conflagration", "野焰之径", ["firesmith_of_lava_forging", "wastelander_of_banditry_desert"]),
      pool("providence", "睿治之径", ["guard_of_wuthering_snow", "genius_of_brilliant_stars"]),
      pool("elixir-seekers", "药使之径", ["longevous_disciple", "messenger_traversing_hackerspace"]),
      pool("darkness", "幽冥之径", ["the_ashblazing_grand_duke", "prisoner_in_deep_confinement"]),
      pool("dreamdive", "梦潜之径", ["pioneer_diver_of_dead_waters", "watchmaker_master_of_dream_machinations"]),
      pool("cavalier", "铁骑之径", ["iron_cavalry_against_the_scourge", "the_wind_soaring_valorous"]),
      pool("uncertainty", "迷识之径", ["sacerdos_relived_ordeal", "scholar_lost_in_erudition"]),
      pool("aria", "凯歌之径", ["hero_of_triumphant_song", "poet_of_mourning_collapse"]),
      pool("thundersurge", "雷涌之径", ["warrior_goddess_of_sun_and_thunder", "wavestrider_captain"]),
      pool("hidden-salvation", "隐救之径", ["world_remaking_deliverer", "self_enshrouded_recluse"]),
      pool("possession", "执迷之径", ["ever_glorious_magical_girl", "diviner_of_distant_reach"]),
    ],
    planar: [
      pool("world-3", "第三世界", ["space_sealing_station", "fleet_of_the_ageless"]),
      pool("world-4", "第四世界", ["pan_cosmic_commercial_enterprise", "belobog_of_the_architects"]),
      pool("world-5", "第五世界", ["celestial_differentiator", "pan_cosmic_commercial_enterprise"]),
      pool("world-6", "第六世界", ["belobog_of_the_architects", "inert_salsotto"]),
      pool("world-7", "第七世界", ["rutilant_arena", "broken_keel"]),
      pool("world-8", "第八世界", ["firmament_frontline_glamoth", "penacony_land_of_the_dreams"]),
      pool("world-9", "第九世界", ["sigonia_the_unclaimed_desolation", "izumo_gensei_and_takama_divine_realm"]),
      pool("du-1", "差分宇宙", ["duran_dynasty_of_running_wolves", "forge_of_the_kalpagni_lantern"]),
      pool("du-2", "差分宇宙：人间喜剧", ["lushaka_the_sunken_seas", "the_wondrous_bananamusement_park"]),
      pool("du-3", "差分宇宙：永恒笑剧", ["amphoreus_the_eternal_land", "bone_collections_serene_demesne"]),
      pool("du-4", "差分宇宙：海隅欢宴", ["revelry_by_the_sea", "giant_tree_of_rapt_brooding"]),
      pool("du-5", "差分宇宙：汇星之城", ["city_of_converging_stars", "punklorde_stage_zero"]),
      pool("du-6", "差分宇宙：织梦乐园", ["tengoku_livestream", "arcadia_of_woven_dreams"]),
    ],
  },
};

export function flattenPools(pools) {
  return [...new Set(pools.flatMap((item) => item.sets))];
}
